import { useEffect, useState } from 'react';
import { request } from './services/api';

const navItems = [['home', 'Overview'], ['receipt', 'Payments'], ['tool', 'Maintenance'], ['file', 'My lease']];
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value ?? 0);

function Icon({ name }) { return <span className={`icon icon-${name}`} aria-hidden="true">{({ home: '⌂', receipt: '▤', tool: '⌁', file: '▱', arrow: '→' })[name] ?? '•'}</span>; }

function Auth({ onSuccess }) {
  const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e) {
    e.preventDefault(); setError(''); setLoading(true); const data = new FormData(e.currentTarget);
    try {
      if (mode === 'login') {
        const body = new URLSearchParams({ username: data.get('email'), password: data.get('password') });
        const result = await request('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body });
        localStorage.setItem('apartmenthub_token', result.access_token); onSuccess();
      } else {
        await request('/auth/signup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_name: data.get('name'), t_email: data.get('email'), password: data.get('password'), t_dob: data.get('dob'), t_phone_no: data.get('phone') }) });
        setMode('login'); setError('Account created. You can now sign in.');
      }
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  }
  return <main className="auth-shell"><section className="auth-story"><div className="brand"><span className="brand-mark">⌂</span> ApartmentHub</div><div><p className="eyebrow">RENTING, MADE SIMPLE</p><h1>A calmer way<br />to feel at home.</h1><p className="story-copy">Keep rent, shared bills and maintenance requests together - beautifully organised and easy to follow.</p></div><div className="quote-card"><span>“</span><p>Everything our home needs, finally in one place.</p></div></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">WELCOME TO APARTMENTHUB</p><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p className="muted">{mode === 'login' ? 'Sign in to see what is happening at home.' : 'Start managing your rental in one calm place.'}</p><form onSubmit={submit}>{mode === 'signup' && <><label>Full name<input required name="name" placeholder="Your name" /></label><label>Date of birth<input required name="dob" type="date" /></label><label>Phone number<input required name="phone" placeholder="98765 43210" /></label></>}<label>Email address<input required name="email" type="email" placeholder="you@example.com" /></label><label>Password<input required name="password" type="password" minLength="8" placeholder="At least 8 characters" /></label>{error && <p className={error.startsWith('Account') ? 'success-text' : 'error'}>{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'} <Icon name="arrow" /></button></form><p className="switch">{mode === 'login' ? 'New to ApartmentHub?' : 'Already have an account?'} <button type="button" onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError(''); }}>{mode === 'login' ? 'Create one' : 'Sign in'}</button></p></div></section></main>;
}

function Overview({ data, tickets, shares }) { return <><section className="welcome"><div><p className="eyebrow">YOUR HOME AT A GLANCE</p><h1>Good morning, {data?.tenant_name?.split(' ')[0] ?? 'there'}.</h1><p className="muted">Here is a gentle overview of your apartment.</p></div><div className="date-pill">◷ {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div></section><section className="stats"><article><span className="stat-icon">₹</span><p>Monthly rent</p><strong>{money(data?.monthly_rent)}</strong><small>Active lease</small></article><article><span className="stat-icon">↗</span><p>Utilities due</p><strong>{money(data?.utilities_due)}</strong><small>{shares.filter(x => x.payment_status !== 'Paid').length} items to review</small></article><article><span className="stat-icon">⌁</span><p>Open requests</p><strong>{data?.open_tickets ?? 0}</strong><small>Maintenance updates</small></article></section><section className="two-column"><article className="panel"><div className="panel-head"><div><p className="eyebrow">UTILITY LEDGER</p><h2>Recent bills</h2></div></div>{shares.slice(0, 3).map(s => <div className="line-item" key={s.share_id}><div className="circle">₹</div><div><strong>Utility bill</strong><p>Due {new Date(s.due_date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</p></div><div className="right"><strong>{money(s.owed_amt)}</strong><span className={`badge ${s.payment_status.replaceAll(' ', '-').toLowerCase()}`}>{s.payment_status}</span></div></div>)}{!shares.length && <Empty text="No utility shares assigned yet." />}</article><article className="panel warm"><p className="eyebrow">MAINTENANCE</p><h2>Home care, sorted.</h2><p className="muted">Raise a request anytime and follow every update in one place.</p><div className="ticket-preview">{tickets[0] ? <><span className="ticket-dot"></span><div><strong>{tickets[0].category}</strong><p>{tickets[0].status} · {tickets[0].description}</p></div></> : <p>No open requests. That is lovely.</p>}</div></article></section></> }
function Payments({ shares, refresh }) { async function pay(id) { await request(`/utilities/${id}/mark-paid`, { method: 'PATCH' }); refresh(); } return <section><div className="page-title"><div><p className="eyebrow">UTILITY LEDGER</p><h1>Payments & bills</h1><p className="muted">Your share of every bill, clearly laid out.</p></div></div><article className="panel table-panel">{shares.length ? shares.map(s => <div className="payment-row" key={s.share_id}><div className="circle">₹</div><div><strong>Shared utility bill</strong><p>Due {new Date(s.due_date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long' })}</p></div><strong>{money(s.owed_amt)}</strong><span className={`badge ${s.payment_status.replaceAll(' ', '-').toLowerCase()}`}>{s.payment_status}</span>{s.payment_status === 'Unpaid' && <button className="soft-button" onClick={() => pay(s.share_id)}>Mark paid</button>}</div>) : <Empty text="No utility bills have been assigned to you yet." />}</article></section> }
function Maintenance({ tickets, refresh }) { const [show, setShow] = useState(false); const [error, setError] = useState(''); async function submit(e) { e.preventDefault(); const form = new FormData(e.currentTarget); try { await request('/tickets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ unit_id: Number(form.get('unit')), category: form.get('category'), description: form.get('description') }) }); setShow(false); refresh(); } catch (err) { setError(err.message); } } return <section><div className="page-title"><div><p className="eyebrow">HOME CARE</p><h1>Maintenance requests</h1><p className="muted">We will keep every update connected to your request.</p></div><button className="primary compact" onClick={() => setShow(!show)}>+ New request</button></div>{show && <form className="panel request-form" onSubmit={submit}><label>Apartment unit ID<input name="unit" type="number" required placeholder="For example: 1" /></label><label>Category<select name="category"><option>Plumbing</option><option>Electrical</option><option>Appliance</option><option>Other</option></select></label><label>What needs attention?<textarea required name="description" placeholder="Tell us what happened and where." /></label>{error && <p className="error">{error}</p>}<button className="primary compact">Send request <Icon name="arrow" /></button></form>}<article className="panel">{tickets.length ? tickets.map(t => <div className="ticket-row" key={t.ticket_id}><span className="ticket-dot"></span><div><strong>{t.category}</strong><p>{t.description}</p><small>Opened {new Date(t.created_at).toLocaleDateString('en-IN')}</small></div><span className={`badge ${t.status.replaceAll(' ', '-').toLowerCase()}`}>{t.status}</span></div>) : <Empty text="No requests yet. Your home is in good shape." />}</article></section> }
function Lease({ leases }) { return <section><div className="page-title"><div><p className="eyebrow">YOUR HOME</p><h1>Lease details</h1><p className="muted">A simple record of your rental agreement.</p></div></div>{leases.length ? leases.map(l => <article className="lease-card" key={l.lease_id}><p className="eyebrow">ACTIVE AGREEMENT</p><h2>Apartment lease</h2><div><span><small>Monthly rent</small><strong>{money(l.monthly_rent)}</strong></span><span><small>Starts</small><strong>{new Date(l.start_date).toLocaleDateString('en-IN')}</strong></span><span><small>Ends</small><strong>{new Date(l.end_date).toLocaleDateString('en-IN')}</strong></span></div></article>) : <article className="panel"><Empty text="No lease has been linked to this account yet." /></article>}</section> }
function Empty({ text }) { return <div className="empty">⌂<p>{text}</p></div> }

export default function App() { const [authenticated, setAuthenticated] = useState(Boolean(localStorage.getItem('apartmenthub_token'))); const [active, setActive] = useState('home'); const [data, setData] = useState(null); const [tickets, setTickets] = useState([]); const [shares, setShares] = useState([]); const [leases, setLeases] = useState([]); const [error, setError] = useState(''); const load = async () => { try { const [d, t, s, l] = await Promise.all([request('/account/dashboard'), request('/tickets/me'), request('/utilities/me'), request('/leases/me')]); setData(d); setTickets(t); setShares(s); setLeases(l); } catch (e) { setError(e.message); if (e.message.includes('token')) { localStorage.removeItem('apartmenthub_token'); setAuthenticated(false); } } }; useEffect(() => { if (authenticated) load(); }, [authenticated]); if (!authenticated) return <Auth onSuccess={() => setAuthenticated(true)} />; const content = active === 'home' ? <Overview data={data} tickets={tickets} shares={shares} /> : active === 'receipt' ? <Payments shares={shares} refresh={load} /> : active === 'tool' ? <Maintenance tickets={tickets} refresh={load} /> : <Lease leases={leases} />; return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">⌂</span> ApartmentHub</div><nav>{navItems.map(([id, label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}><Icon name={id} />{label}</button>)}</nav><div className="side-foot"><p>YOUR SPACE, SIMPLIFIED</p><button onClick={() => { localStorage.removeItem('apartmenthub_token'); setAuthenticated(false); }}>Sign out</button></div></aside><main className="dashboard-main">{error && <p className="error banner">{error}</p>}{content}</main></div> }
