import { useEffect, useState } from 'react';
import MaintenanceForm from './components/MaintenanceForm';
import { request } from './services/api';

const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value ?? 0);

function Auth({ onSuccess }) {
  const [mode, setMode] = useState('login'); const [choice, setChoice] = useState('tenant'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) {
    event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget);
    try {
      if (mode === 'signup') await request('/auth/signup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_name: form.get('name'), t_email: form.get('email'), password: form.get('password'), t_dob: form.get('dob'), t_phone_no: form.get('phone') }) });
      const login = await request('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ username: form.get('email'), password: form.get('password') }) });
      if (mode === 'login' && choice !== login.role) throw new Error(`This account is a ${login.role}. Select that role first.`);
      localStorage.setItem('apartmenthub_token', login.access_token); localStorage.setItem('apartmenthub_role', login.role); onSuccess(login.role, mode === 'signup');
    } catch (e) { setError(e.message); } finally { setLoading(false); }
  }
  return <main className="auth-shell"><section className="auth-story"><div className="brand"><span className="brand-mark">⌂</span> ApartmentHub</div><div><p className="eyebrow">ONE HOME, ONE PLACE</p><h1>Every rental<br />detail, connected.</h1></div></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">WELCOME TO APARTMENTHUB</p><h2>{mode === 'login' ? 'Sign in' : 'Create a tenant account'}</h2><div className="role-picker">{['tenant','admin','landlord'].map(role => <button type="button" key={role} className={choice === role ? 'selected' : ''} onClick={() => setChoice(role)}><strong>{role}</strong></button>)}</div><form onSubmit={submit}>{mode === 'signup' && <><label>Full name<input name="name" required /></label><label>Date of birth<input name="dob" type="date" required /></label><label>Phone number<input name="phone" required /></label></>}<label>Email address<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength="8" required /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'} →</button></form><p className="switch">{mode === 'login' ? 'New tenant?' : 'Already have an account?'} <button type="button" onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError(''); }}>{mode === 'login' ? 'Create one' : 'Sign in'}</button></p></div></section></main>;
}

function Setup({ done }) {
  const [message, setMessage] = useState('');
  async function submit(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); for (const k of Object.keys(values)) if (!values[k]) values[k] = null; for (const k of ['existing_unit_id','base_rent','monthly_rent','deposit_amount']) if (values[k] !== null) values[k] = Number(values[k]); try { const result = await request('/account/setup', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(values) }); if (!result.created) throw new Error(result.message); setMessage('Saved successfully.'); } catch(e) { setMessage(e.message); } }
  return <main className="setup-page"><div className="setup-card"><p className="eyebrow">OPTIONAL ACCOUNT SETUP</p><h1>Complete your rental profile.</h1><p className="muted">Add these details now or skip them. You can create an apartment and lease, or link an existing unit.</p><form onSubmit={submit}><label>Existing apartment unit ID (optional)<input name="existing_unit_id" type="number" min="1" placeholder="Example: 3" /></label><p className="divider">OR CREATE A NEW APARTMENT</p><div className="form-grid"><label>Building name<input name="building_name" /></label><label>Unit number<input name="unit_no" /></label><label>Street<input name="street" /></label><label>Pincode<input name="pincode" /></label><label>Base rent<input name="base_rent" type="number" min="0" /></label></div><p className="divider">OPTIONAL LEASE</p><div className="form-grid"><label>Start date<input name="start_date" type="date" /></label><label>End date<input name="end_date" type="date" /></label><label>Monthly rent<input name="monthly_rent" type="number" min="0" /></label><label>Security deposit<input name="deposit_amount" type="number" min="0" /></label></div>{message && <p className={message.startsWith('Saved') ? 'success-text' : 'error'}>{message}</p>}<div className="actions"><button className="primary">Save setup</button><button type="button" className="soft-button" onClick={done}>Skip for now</button></div></form></div></main>;
}

function Shell({ title, tabs, active, setActive, children, logout }) { return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">⌂</span>{title}</div><nav>{tabs.map(([id,label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{label}</button>)}</nav><div className="side-foot"><button onClick={logout}>Sign out</button></div></aside><main className="dashboard-main">{children}</main></div>; }
function Empty({ text }) { return <div className="empty">⌂<p>{text}</p></div>; }

function TenantHome({ logout }) {
  const [tab, setTab] = useState('home'); const [data, setData] = useState({}); const [tickets, setTickets] = useState([]); const [leases, setLeases] = useState([]); const [shares, setShares] = useState([]); const [error, setError] = useState('');
  const load = async () => { try { const [d,t,l,s] = await Promise.all([request('/account/dashboard'),request('/tickets/me'),request('/leases/me'),request('/utilities/me')]); setData(d); setTickets(t); setLeases(l); setShares(s); } catch(e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  return <Shell title="ApartmentHub" tabs={[['home','Overview'],['tickets','Maintenance'],['lease','My lease']]} active={tab} setActive={setTab} logout={logout}>{error && <p className="error banner">{error}</p>}{tab === 'home' && <><section className="welcome"><div><p className="eyebrow">YOUR HOME AT A GLANCE</p><h1>Hello, {data.tenant_name ?? 'there'}.</h1><p className="muted">Your apartment details, in one calm place.</p></div></section><section className="stats"><article><p>Monthly rent</p><strong>{money(data.monthly_rent)}</strong></article><article><p>Utilities due</p><strong>{money(data.utilities_due)}</strong></article><article><p>Open requests</p><strong>{data.open_tickets ?? 0}</strong></article></section><section className="two-column"><article className="panel"><p className="eyebrow">RECENT BILLS</p>{shares.slice(0,3).map(s => <div className="line-item" key={s.share_id}><span>Utility bill</span><strong>{money(s.owed_amt)}</strong><span className="badge unpaid">{s.payment_status}</span></div>)}{!shares.length && <Empty text="No utility bills assigned yet." />}</article><article className="panel warm"><p className="eyebrow">MAINTENANCE</p><h2>{tickets[0]?.category ?? 'All clear'}</h2><p className="muted">{tickets[0]?.description ?? 'Create a ticket whenever something needs attention.'}</p></article></section></>}{tab === 'tickets' && <><div className="page-title"><div><p className="eyebrow">HOME CARE</p><h1>Maintenance requests</h1><p className="muted">Every submission adds a ticket for your own tenant ID.</p></div></div><MaintenanceForm onCreated={load} /><article className="panel">{tickets.map(t => <div className="ticket-row" key={t.ticket_id}><div><strong>{t.category}</strong><p>{t.description}</p><small>Ticket #{t.ticket_id}</small></div><span className="badge unpaid">{t.status}</span></div>)}{!tickets.length && <Empty text="No maintenance tickets yet." />}</article></>}{tab === 'lease' && <><div className="page-title"><div><p className="eyebrow">YOUR HOME</p><h1>Lease details</h1></div></div>{leases.map(l => <article className="lease-card" key={l.lease_id}><h2>Apartment lease</h2><div><span><small>Monthly rent</small><strong>{money(l.monthly_rent)}</strong></span><span><small>Starts</small><strong>{l.start_date}</strong></span><span><small>Ends</small><strong>{l.end_date}</strong></span></div></article>)}{!leases.length && <Empty text="No lease linked yet. Use setup after a new signup." />}</>}</Shell>;
}

function AdminHome({ logout }) {
  const [tables, setTables] = useState([]); const [table, setTable] = useState('tenants'); const [rows, setRows] = useState([]); const [draft, setDraft] = useState('{}'); const [error, setError] = useState('');
  const load = async name => { try { setRows(await request(`/admin/${name ?? table}`)); setError(''); } catch(e) { setError(e.message); } };
  useEffect(() => { request('/admin/tables').then(x => { setTables(x); load('tenants'); }).catch(e => setError(e.message)); }, []);
  async function save(method, id) { try { await request(`/admin/${table}${id ? `/${id}` : ''}`, { method, headers: {'Content-Type':'application/json'}, body: draft }); setDraft('{}'); load(); } catch(e) { setError(e.message); } }
  return <Shell title="ApartmentHub Admin" tabs={tables.map(t => [t,t.replaceAll('_',' ')])} active={table} setActive={x => { setTable(x); load(x); }} logout={logout}><section><div className="page-title"><div><p className="eyebrow">DATABASE CONTROL ROOM</p><h1>{table.replaceAll('_',' ')}</h1><p className="muted">View, edit, insert and remove the records in every project table.</p></div><button className="soft-button" onClick={() => load()}>Refresh</button></div>{error && <p className="error banner">{error}</p>}<article className="panel admin-table">{rows.map(row => <div className="admin-row" key={Object.values(row)[0]}><pre>{JSON.stringify(row, null, 2)}</pre><div><button className="soft-button" onClick={() => setDraft(JSON.stringify(row, null, 2))}>Edit</button><button className="danger-button" onClick={() => { if (confirm('Delete this record?')) save('DELETE', Object.values(row)[0]); }}>Delete</button></div></div>)}{!rows.length && <Empty text="No rows in this table." />}</article><article className="panel admin-editor"><p className="eyebrow">EDIT OR INSERT JSON</p><textarea value={draft} onChange={e => setDraft(e.target.value)} /><div className="actions"><button className="primary" onClick={() => save('POST')}>Insert record</button><button className="soft-button" onClick={() => { try { save('PATCH', Object.values(JSON.parse(draft))[0]); } catch { setError('Use valid JSON including the record ID.'); } }}>Update selected JSON</button></div></article></section></Shell>;
}

export default function AppV2() {
  const [role, setRole] = useState(localStorage.getItem('apartmenthub_role')); const [setup, setSetup] = useState(false); const token = localStorage.getItem('apartmenthub_token'); const logout = () => { localStorage.clear(); location.reload(); };
  if (!token || !role) return <Auth onSuccess={(newRole, needsSetup) => { setRole(newRole); setSetup(needsSetup); }} />;
  if (setup && role === 'tenant') return <Setup done={() => setSetup(false)} />;
  if (role === 'admin') return <AdminHome logout={logout} />;
  if (role === 'landlord') return <Shell title="ApartmentHub Landlord" tabs={[]} active="" setActive={() => {}} logout={logout}><article className="panel"><p className="eyebrow">COMING SOON</p><h1>Landlord workspace</h1><p className="muted">Maintenance ticket handling will be added here next.</p></article></Shell>;
  return <TenantHome logout={logout} />;
}
